/**
 * Test vectors for the shared crypto contract (spec §6.3, §17.3).
 *
 * These are the "known input / expected output" fixtures the spec requires so
 * Web (Web Crypto) and Swift (CryptoKit) implementations can be compared byte
 * for byte. The expected values are generated by the reference implementation
 * in this repository and MUST be verified by a second implementation before
 * being treated as an independent check; the fixture *inputs* are fixed and
 * the derived values are deterministic.
 */

import { describe, expect, it } from "vitest";

import {
  aesGcmDecrypt,
  aesGcmEncrypt,
  deriveDraftKey,
  deriveDocumentKey,
  deriveKek,
  deriveRecoveryAuth,
  deriveRecoveryKek,
  documentAad,
  draftAad,
  formatRecoveryKey,
  mediaChunkAad,
  mediaChunkNonce,
  parseRecoveryKey,
  recoveryAad,
  sha256,
  unwrapVaultKey,
  vaultKeyAad,
  wrapVaultKey,
} from "../../packages/protocol/src/index.ts";
import {
  CHUNK_CIPHER_BYTES,
  CHUNK_PLAIN_BYTES,
  PRF_INPUT_V1,
} from "../../packages/protocol/src/crypto.ts";
import { encode, utf8, uuidToBytes } from "../../packages/protocol/src/encode.ts";
import { fromBase64Url, toBase64Url } from "../../packages/protocol/src/base64url.ts";

const ACCOUNT_ID = "8cf3a2b1-0000-4000-8000-000000000001";
const DOCUMENT_ID = "8cf3a2b1-0000-4000-8000-000000000002";
const CREDENTIAL_ID = new Uint8Array([
  0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32,
  0x10,
]);
const MUTATION_ID = "8cf3a2b1-0000-4000-8000-000000000003";
const SEED = new Uint8Array(32).fill(0x42);
const VAULT_KEY = new Uint8Array(32).fill(0x17);
const WRAP_SALT = new Uint8Array(32).fill(0x99);

function hex(bytes: Uint8Array): string {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}

describe("Encode (spec §6.3)", () => {
  it("prefixes each field with a uint32 big-endian length", () => {
    expect(hex(encode("ab"))).toBe("000000026162");
    expect(hex(encode("", "a"))).toBe("000000000000000161");
    expect(hex(encode(1))).toBe("000000080000000000000001");
    expect(hex(encode(0))).toBe("000000080000000000000000");
  });

  it("encodes uint64 big-endian at the top of the range", () => {
    expect(hex(encode(9007199254740991))).toBe("00000008001fffffffffffff");
  });

  it("treats UUIDs as 16 raw bytes", () => {
    const bytes = uuidToBytes(ACCOUNT_ID);
    expect(bytes.byteLength).toBe(16);
    expect(hex(bytes)).toBe("8cf3a2b1000040008000000000000001");
    expect(hex(encode(bytes))).toBe("000000108cf3a2b1000040008000000000000001");
  });

  it("rejects negative and out-of-range integers", () => {
    expect(() => encode(-1)).toThrow(RangeError);
    expect(() => encode(18446744073709551616n)).toThrow(RangeError);
  });

  it("does not depend on JSON key ordering or locale strings", () => {
    // Two logically identical field lists must produce identical bytes
    // regardless of how a caller built them.
    const a = encode("txt/v1/document-key", uuidToBytes(DOCUMENT_ID), 1);
    const b = encode("txt/v1/document-key", uuidToBytes(DOCUMENT_ID), 1);
    expect(hex(a)).toBe(hex(b));
  });
});

describe("base64url (spec §6.3)", () => {
  it("round-trips without padding", () => {
    for (const length of [0, 1, 2, 3, 4, 5, 8, 12, 16, 31, 32, 33, 100]) {
      const bytes = new Uint8Array(length).map((_, i) => (i * 37) % 256);
      const text = toBase64Url(bytes);
      expect(text).not.toContain("=");
      expect(text).not.toMatch(/[+/]/);
      expect(hex(fromBase64Url(text))).toBe(hex(bytes));
    }
  });

  it("rejects invalid characters", () => {
    expect(() => fromBase64Url("a+b")).toThrow(TypeError);
    expect(() => fromBase64Url("a=")).toThrow(TypeError);
  });
});

describe("PRF input (spec §6.2)", () => {
  it("is the fixed SHA-256 of the versioned public string", async () => {
    const expected = await sha256(utf8("txt.2-38.com/prf-input/v1"));
    expect(hex(PRF_INPUT_V1)).toBe(hex(expected));
    expect(PRF_INPUT_V1.byteLength).toBe(32);
  });
});

describe("AES-256-GCM (spec §6.3)", () => {
  it("uses ciphertext||tag with a separate 12-byte nonce", async () => {
    const key = new Uint8Array(32).fill(0x01);
    const nonce = new Uint8Array(12).fill(0x02);
    const aad = utf8("aad");
    const plaintext = utf8("hello");
    const ct = await aesGcmEncrypt(key, nonce, plaintext, aad);
    expect(ct.byteLength).toBe(plaintext.byteLength + 16);
    expect(hex(await aesGcmDecrypt(key, nonce, ct, aad))).toBe(hex(plaintext));
  });

  it("rejects a modified tag or AAD", async () => {
    const key = new Uint8Array(32).fill(0x01);
    const nonce = new Uint8Array(12).fill(0x02);
    const ct = await aesGcmEncrypt(key, nonce, utf8("hello"), utf8("aad"));
    const tampered = ct.slice();
    tampered[0] = (tampered[0] as number) ^ 0xff;
    await expect(aesGcmDecrypt(key, nonce, tampered, utf8("aad"))).rejects.toThrow();
    await expect(aesGcmDecrypt(key, nonce, ct, utf8("aad2"))).rejects.toThrow();
  });
});

describe("known-answer vectors", () => {
  it("KEK / wrapped VaultKey are reproducible from fixed inputs", async () => {
    const prfOutput = new Uint8Array(32).fill(0x5a);
    const kek = await deriveKek(prfOutput, WRAP_SALT, ACCOUNT_ID, CREDENTIAL_ID);
    expect(hex(kek)).toMatchSnapshot();
    expect(kek.byteLength).toBe(32);

    const aad = vaultKeyAad(1, 1, ACCOUNT_ID, CREDENTIAL_ID);
    const { nonce, wrappedKey } = await wrapVaultKey(VAULT_KEY, kek, aad);
    expect(nonce.byteLength).toBe(12);
    expect(wrappedKey.byteLength).toBe(48); // 32 + 16 tag
    const unwrapped = await unwrapVaultKey(kek, nonce, wrappedKey, aad);
    expect(hex(unwrapped)).toBe(hex(VAULT_KEY));
  });

  it("document key and AAD are reproducible from fixed inputs", async () => {
    const key = await deriveDocumentKey(VAULT_KEY, MUTATION_ID, ACCOUNT_ID, DOCUMENT_ID, 1);
    expect(hex(key)).toMatchSnapshot();
    expect(hex(documentAad(1, 1, ACCOUNT_ID, DOCUMENT_ID, MUTATION_ID, 18))).toMatchSnapshot();
  });

  it("draft key and AAD use separate purpose names", async () => {
    const draftId = "8cf3a2b1-0000-4000-8000-000000000004";
    const key = await deriveDraftKey(VAULT_KEY, draftId, ACCOUNT_ID, DOCUMENT_ID, 1);
    const docKey = await deriveDocumentKey(VAULT_KEY, draftId, ACCOUNT_ID, DOCUMENT_ID, 1);
    expect(hex(key)).not.toBe(hex(docKey));
    expect(hex(draftAad(ACCOUNT_ID, DOCUMENT_ID, "tab-1", 1))).toMatchSnapshot();
  });

  it("recovery key derives auth/KEK and round-trips its text form", async () => {
    const auth = await deriveRecoveryAuth(SEED, ACCOUNT_ID);
    const kek = await deriveRecoveryKek(SEED, ACCOUNT_ID);
    expect(hex(auth)).toMatchSnapshot();
    expect(hex(kek)).toMatchSnapshot();

    const text = await formatRecoveryKey(ACCOUNT_ID, SEED);
    expect(text.startsWith("TXT1.")).toBe(true);
    expect(text.split(".")).toHaveLength(4);
    const parsed = await parseRecoveryKey(text);
    expect(parsed.accountId).toBe(ACCOUNT_ID);
    expect(hex(parsed.seed)).toBe(hex(SEED));
  });

  it("recovery key detects input errors via its checksum", async () => {
    const text = await formatRecoveryKey(ACCOUNT_ID, SEED);
    const parts = text.split(".");
    const broken = `${parts[0]}.${parts[1]}.${parts[2]}.${toBase64Url(new Uint8Array(4).fill(7))}`;
    await expect(parseRecoveryKey(broken)).rejects.toThrow(/checksum/);
    await expect(parseRecoveryKey("nope")).rejects.toThrow();
  });

  it("media chunk nonce and AAD match the container definition", async () => {
    const mediaId = "8cf3a2b1-0000-4000-8000-000000000005";
    const prefix = new Uint8Array(8).fill(0xaa);
    expect(hex(mediaChunkNonce(prefix, 0))).toBe("aaaaaaaaaaaaaaaa00000000");
    expect(hex(mediaChunkNonce(prefix, 3))).toBe("aaaaaaaaaaaaaaaa00000003");
    expect(
      hex(mediaChunkAad(1, ACCOUNT_ID, DOCUMENT_ID, mediaId, 0, 100, 100)),
    ).toMatchSnapshot();
  });

  it("cipher length math matches the 1MiB + 16B chunk layout", () => {
    expect(CHUNK_PLAIN_BYTES).toBe(1_048_576);
    expect(CHUNK_CIPHER_BYTES).toBe(1_048_592);
    // 512MiB plaintext -> 536,879,104 bytes ciphertext (spec §11.1)
    const plain = 536_870_912;
    const chunks = Math.ceil(plain / CHUNK_PLAIN_BYTES);
    expect(chunks).toBe(512);
    expect(plain + chunks * 16).toBe(536_879_104);
  });
});
